"""Runtime layout helpers for the local JD bridge.

Editable installs use ``tools/jd-bridge`` in the repo. Packaged installs ship
the bridge source as data files, then copy it into a user-writable runtime
directory so ``npm install`` and ``.env`` never mutate site-packages.
"""
from __future__ import annotations

import os
import shutil
import sys
import textwrap
from importlib import metadata
from pathlib import Path


BRIDGE_FILES = ("package.json", "package-lock.json", ".env.example")
BRIDGE_DIRS = ("src", "config")
VAULT_LINKS = ("data", "docs", "jobs", "output")


def repo_root(framework_root: Path) -> Path | None:
    """Return the editable-clone repo root, or None for wheel/pipx installs."""
    for parent in [framework_root, *framework_root.parents]:
        if (parent / "pyproject.toml").exists() and (parent / "tools" / "jd-bridge").is_dir():
            return parent
    return None


def tailord_data_dir() -> Path:
    raw = os.environ.get("XDG_DATA_HOME")
    base = Path(raw).expanduser() if raw else Path.home() / ".local" / "share"
    return base / "tailord"


def bridge_runtime_dir() -> Path:
    raw = os.environ.get("TAILORD_BRIDGE_DIR")
    return Path(raw).expanduser().resolve() if raw else tailord_data_dir() / "jd-bridge"


def framework_workspace_dir() -> Path:
    raw = os.environ.get("TAILORD_FRAMEWORK_DIR")
    return Path(raw).expanduser().resolve() if raw else tailord_data_dir() / "framework"


def _installed_data_bridge_dir() -> Path | None:
    candidates = [
        Path(sys.prefix) / "share" / "tailord" / "jd-bridge",
        Path(sys.prefix) / "tailord" / "jd-bridge",
    ]
    for candidate in candidates:
        if (candidate / "package.json").is_file():
            return candidate

    try:
        files = metadata.files("tailord")
    except metadata.PackageNotFoundError:
        return None

    for file in files or []:
        normalized = str(file).replace("\\", "/")
        if normalized.endswith("share/tailord/jd-bridge/package.json"):
            located = Path(file.locate()).resolve()
            if located.is_file():
                return located.parent
    return None


def bridge_source_dir(framework_root: Path) -> Path:
    raw = os.environ.get("TAILORD_BRIDGE_SOURCE")
    if raw:
        source = Path(raw).expanduser().resolve()
        if (source / "package.json").is_file():
            return source
        raise FileNotFoundError(f"TAILORD_BRIDGE_SOURCE does not look like jd-bridge: {source}")

    repo = repo_root(framework_root)
    if repo is not None:
        return repo / "tools" / "jd-bridge"

    installed = _installed_data_bridge_dir()
    if installed is not None:
        return installed

    raise FileNotFoundError(
        "bundled jd-bridge assets are missing. Reinstall tailord from a build "
        "that includes share/tailord/jd-bridge."
    )


def _copy_bridge_assets(source: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for name in BRIDGE_FILES:
        src = source / name
        if src.is_file():
            shutil.copy2(src, dest / name)
    for name in BRIDGE_DIRS:
        src = source / name
        dst = dest / name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)


def ensure_bridge_runtime(framework_root: Path) -> Path:
    source = bridge_source_dir(framework_root)
    repo = repo_root(framework_root)
    if repo is not None and source == repo / "tools" / "jd-bridge":
        return source

    dest = bridge_runtime_dir()
    if source.resolve() != dest.resolve():
        _copy_bridge_assets(source, dest)
    return dest


def _copy_claude_skills(source_root: Path, workspace: Path) -> None:
    if not source_root.is_dir():
        raise FileNotFoundError(f"packaged skill source is missing: {source_root}")

    out_root = workspace / ".claude" / "skills"
    out_root.mkdir(parents=True, exist_ok=True)
    expected: set[Path] = set()

    for skill_dir in sorted(p for p in source_root.iterdir() if p.is_dir()):
        target_dir = out_root / skill_dir.name
        if target_dir.exists():
            shutil.rmtree(target_dir)
        shutil.copytree(skill_dir, target_dir)
        expected.update(p for p in target_dir.rglob("*") if p.is_file())

    for path in sorted(out_root.rglob("*"), reverse=True):
        if path.is_file() and path not in expected:
            path.unlink()
        elif path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def _write_makefile(workspace: Path) -> None:
    text = textwrap.dedent(f"""\
        # Generated by `tailord setup-bridge`.
        # This tiny workspace lets the Claude CLI discover Tailord skills while
        # rendering with the Python package installed by pipx/pip.

        PYTHON ?= {sys.executable}
        VAULT ?= $(if $(RESUME_VAULT),$(RESUME_VAULT),$(CURDIR))
        export RESUME_VAULT := $(VAULT)

        .PHONY: validate build-job build-cover-job

        validate:
        \t$(PYTHON) -m tailord.validate

        build-job:
        \t@test -n "$(JOB)" || (echo "JOB=path/to/variant.yaml is required" && exit 2)
        \t$(PYTHON) -m tailord.render --variant $(JOB) --out $(dir $(JOB))resume.html
        \t$(PYTHON) -m tailord.build --variant $(JOB) --out-dir $(dir $(JOB)) --out-name resume

        build-cover-job:
        \t@test -n "$(JOB)" || (echo "JOB=path/to/cover-letter.yaml is required" && exit 2)
        \t$(PYTHON) -m tailord.cover_letter --variant $(JOB) --out-dir $(dir $(JOB)) --out-name cover-letter
        """)
    (workspace / "Makefile").write_text(text, encoding="utf-8")


def _refresh_vault_links(workspace: Path, vault: Path) -> None:
    for name in VAULT_LINKS:
        target = vault / name
        if not target.exists():
            continue
        link = workspace / name
        if link.is_symlink():
            if link.resolve() == target.resolve():
                continue
            link.unlink()
        elif link.exists():
            continue
        try:
            link.symlink_to(target, target_is_directory=target.is_dir())
        except OSError:
            # The prompt passes absolute vault paths, so symlinks are a convenience
            # for skill instructions that mention data/master.yaml relatively.
            pass


def ensure_framework_workspace(framework_root: Path, vault: Path) -> Path:
    repo = repo_root(framework_root)
    if repo is not None:
        return repo

    workspace = framework_workspace_dir()
    workspace.mkdir(parents=True, exist_ok=True)
    _copy_claude_skills(framework_root / "skills", workspace)
    _write_makefile(workspace)
    _refresh_vault_links(workspace, vault)
    return workspace
