"""Sync source skills to per-client output directories.

Source of truth: `src/tailord/skills/<name>/SKILL.md`. Outputs are written
to `.claude/skills/`, `.codex/skills/`, `.opencode/skills/` at the framework
root and committed to git so a fresh clone works with any supported runtime
without an extra setup step. Each output gets an HTML-comment marker as the
first body line so a reader landing in the generated tree knows where the
source is.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml


CLIENTS = ("claude", "codex", "opencode")


def _generated_marker(client: str, source_rel: str) -> str:
    return (
        f"<!-- generated by `tailord sync-skills` for {client} from "
        f"{source_rel} — do not edit -->"
    )


@dataclass
class Skill:
    name: str
    source_dir: Path
    frontmatter: dict
    body: str
    topic_files: list[Path]


def _parse_skill_md(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing YAML frontmatter (must start with `---`)")
    try:
        _, fm_text, body = text.split("---\n", 2)
    except ValueError as e:
        raise ValueError(f"{path}: malformed frontmatter (no closing `---`)") from e
    fm = yaml.safe_load(fm_text) or {}
    return fm, body.lstrip("\n")


def _load_skill(skill_dir: Path) -> Skill:
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        raise FileNotFoundError(f"{skill_dir}: no SKILL.md")
    fm, body = _parse_skill_md(skill_md)
    if "name" not in fm or "description" not in fm:
        raise ValueError(f"{skill_md}: frontmatter must include `name` and `description`")
    if fm["name"] != skill_dir.name:
        raise ValueError(
            f"{skill_md}: frontmatter name `{fm['name']}` does not match dir `{skill_dir.name}`"
        )
    topic_files = sorted(p for p in skill_dir.glob("*.md") if p.name != "SKILL.md")
    return Skill(
        name=fm["name"],
        source_dir=skill_dir,
        frontmatter={"name": fm["name"], "description": fm["description"]},
        body=body,
        topic_files=topic_files,
    )


def _render_skill_md(skill: Skill, client: str, source_rel: str) -> str:
    # width=10**9 keeps `description` on a single line (yaml's default
    # folds long strings, which most skill loaders tolerate but is ugly to
    # diff and inconsistent with the hand-written source).
    fm = yaml.safe_dump(
        skill.frontmatter,
        sort_keys=False,
        allow_unicode=True,
        width=10**9,
    ).strip()
    marker = _generated_marker(client, source_rel)
    return f"---\n{fm}\n---\n\n{marker}\n\n{skill.body}".rstrip() + "\n"


def _collect_skills(source_root: Path) -> list[Skill]:
    if not source_root.exists():
        raise FileNotFoundError(f"source skills dir does not exist: {source_root}")
    skills = []
    for entry in sorted(source_root.iterdir()):
        if not entry.is_dir():
            continue
        skills.append(_load_skill(entry))
    if not skills:
        raise ValueError(f"no skills found under {source_root}")
    return skills


def _expected_outputs(skill: Skill, source_root: Path, framework_root: Path) -> dict[Path, str]:
    out: dict[Path, str] = {}
    source_rel = str(skill.source_dir.relative_to(framework_root) / "SKILL.md")
    for client in CLIENTS:
        client_dir = framework_root / f".{client}" / "skills" / skill.name
        out[client_dir / "SKILL.md"] = _render_skill_md(skill, client, source_rel)
        for topic in skill.topic_files:
            out[client_dir / topic.name] = topic.read_text(encoding="utf-8")
    return out


def _write_outputs(expected: dict[Path, str]) -> list[Path]:
    written: list[Path] = []
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written.append(path)
    return written


def _clean_stale(framework_root: Path, expected_paths: set[Path]) -> list[Path]:
    """Remove files under .<client>/skills/ that the source no longer produces."""
    removed: list[Path] = []
    for client in CLIENTS:
        client_root = framework_root / f".{client}" / "skills"
        if not client_root.exists():
            continue
        for path in client_root.rglob("*"):
            if path.is_file() and path not in expected_paths:
                path.unlink()
                removed.append(path)
        for path in sorted(client_root.rglob("*"), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    return removed


def _check(expected: dict[Path, str]) -> list[str]:
    diffs: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            diffs.append(f"missing: {path}")
        elif path.read_text(encoding="utf-8") != content:
            diffs.append(f"stale:   {path}")
    return diffs


def run(framework_root: Path, *, check_only: bool = False) -> int:
    source_root = framework_root / "src" / "tailord" / "skills"
    skills = _collect_skills(source_root)

    expected: dict[Path, str] = {}
    for skill in skills:
        expected.update(_expected_outputs(skill, source_root, framework_root))

    if check_only:
        diffs = _check(expected)
        expected_paths = set(expected.keys())
        for client in CLIENTS:
            client_root = framework_root / f".{client}" / "skills"
            if not client_root.exists():
                continue
            for path in client_root.rglob("*"):
                if path.is_file() and path not in expected_paths:
                    diffs.append(f"extra:   {path}")
        if diffs:
            print("sync-skills --check: outputs are stale", file=sys.stderr)
            for d in sorted(diffs):
                print(f"  {d}", file=sys.stderr)
            print("\nRun `tailord sync-skills` and commit the changes.", file=sys.stderr)
            return 1
        print(f"sync-skills: {len(skills)} skill(s) × {len(CLIENTS)} client(s), all up to date")
        return 0

    written = _write_outputs(expected)
    removed = _clean_stale(framework_root, set(expected.keys()))
    print(f"sync-skills: {len(skills)} skill(s) × {len(CLIENTS)} client(s)")
    if written:
        print(f"  wrote {len(written)} file(s)")
        for p in written:
            print(f"    + {p.relative_to(framework_root)}")
    if removed:
        print(f"  removed {len(removed)} stale file(s)")
        for p in removed:
            print(f"    - {p.relative_to(framework_root)}")
    if not written and not removed:
        print("  no changes")
    return 0


def _detect_repo_root(start: Path) -> Path | None:
    """Walk up from `start` looking for a directory that contains both
    `pyproject.toml` AND `src/tailord/skills/` — i.e. an editable clone of
    the framework repo. Returns None for wheel/pipx installs where the
    source tree isn't present."""
    for parent in [start, *start.parents]:
        if (parent / "pyproject.toml").exists() and (parent / "src" / "tailord" / "skills").is_dir():
            return parent
    return None


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="tailord sync-skills",
        description="Sync source skills to .claude/, .codex/, .opencode/ output dirs.",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if outputs are stale (no writes); used in CI",
    )
    p.add_argument(
        "--framework-root",
        type=Path,
        default=None,
        help="repo root containing src/tailord/skills/ (default: auto-detect)",
    )
    args = p.parse_args(argv)

    if args.framework_root:
        framework_root = args.framework_root.resolve()
    else:
        from tailord.config import FRAMEWORK_ROOT
        detected = _detect_repo_root(FRAMEWORK_ROOT)
        if detected is None:
            print(
                "sync-skills must be run from a clone of the framework repo "
                "(source `src/tailord/skills/` not found from "
                f"{FRAMEWORK_ROOT}).\n"
                "Pass --framework-root explicitly or `git clone "
                "https://github.com/sarthak22gaur/tailord.git`.",
                file=sys.stderr,
            )
            return 2
        framework_root = detected
    return run(framework_root, check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
